// Category.ts
export enum Category {
  MUSIC = "MUSIC",
  PODCAST = "PODCAST",
  CONVERSATION = "CONVERSATION",
  CONFESSION = "CONFESSION",
  NEWS = "NEWS",
  EDUCATION = "EDUCATION",
  OTHER = "OTHER",
}
